# Generated by Django 5.1.6 on 2025-03-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('processing', 'Processing'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('content', models.TextField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.CharField(max_length=13, unique=True)),
                ('status', models.CharField(choices=[('F', 'Failed'), ('U', 'Unvalidated'), ('V', 'Validated')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_point_id', models.CharField(max_length=10, unique=True)),
                ('meter_type', models.CharField(choices=[('C', 'Customer own read'), ('D', 'Deemed or Estimated')], default='C', max_length=1)),
                ('mpan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor_app.mpan')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_register_id', models.CharField(max_length=2)),
                ('reading_date', models.DateTimeField()),
                ('reading_value', models.DecimalField(decimal_places=1, max_digits=10)),
                ('reading_flag', models.CharField(choices=[('T', 'Valid'), ('N', 'Suspect')], default='T', max_length=1)),
                ('reading_method', models.CharField(choices=[('N', 'Not viewed by an Agent or non site visit'), ('P', 'Viewed by an Agent or site visit')], max_length=1)),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor_app.flowfile')),
                ('meter_reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor_app.meterreader')),
            ],
        ),
    ]
